### ISSUE TITLE
Provide contribution instructions

### ISSUE THREAD

**Issue by dmitry-fa** [googleapis/api-common-java#145]
- "How to Contribute" document https://github.com/googleapis/api-common-java/blob/master/CONTRIBUTING.md gives no instructions on how to build and test a change.

- Reference to  `the CONTRIBUTING documentation` from https://github.com/googleapis/api-common-java/blob/master/README.md is incorrect

**Comment by miraleung** [comment]
Thanks for filing an issue. The `CONTRIBUTING` doc is standard across `googleapis` repos, but I've added some build/test steps to the main `README` and fixed the links in PR #153.
