### ISSUE TITLE
How to return PathTemplate with complex resource identifiers?

### ISSUE THREAD

**Issue by devchas** [googleapis/api-common-java#154]
I see you added support for complex resource identifiers with #125. However, I can't seem to figure out how to correctly return the instantiated template with populated variable values. For example, let's say I have a template `customers/{customer_id}/adGroupAds/{ad_group_id}~{ad_id}`. I can create the PathTemplate, which recognizes the `~` character as a separator. However, when I call the `instantiate(String... keysAndValues)` method like so `PATH_TEMPLATE.instantiate("customer_id", customerId, "ad_group_id", adGroupId, "ad_id", adId)`, the string returned does not have the `~` separator. The String that is returned is `customers/1234/adGroupAds/5678/1011` instead of the expected `customers/1234/adGroupAds/5678~1011`.

Is there a way to do this so that the resulting string still contains the complex resource identifier? Or did #125 not address this?

**Comment by miraleung** [comment]
Could you please link to the `instantiate` method mentioned above?

**Comment by devchas** [comment]
Here is the [link](https://github.com/googleapis/api-common-java/blob/39612f1f2f385228f0e03e6667dc9627c9ff18ab/src/main/java/com/google/api/pathtemplate/PathTemplate.java#L706).

**Comment by aohren** [comment]
This causes our the *Name.java classes to generate incorrect resource names when non `/` separators are in the URL pattern. It can parse them OK, but when you convert back to a String, the underlying PathTemplate doesn't `remember` the separator character; it assumes all separators are `/`s:

An example below:
```
String resourceNmae = "customers/123456789/adGroupAds/9876565423~082734345";
System.out.printf("input resource name: %s\n", resourceNmae);
AdGroupAdName n = AdGroupAdName.parse(resourceNmae);
System.out.printf("output resource name: %s\n", n.toString());
```
Produces:
```
input resource name: customers/123456789/adGroupAds/9876565423~082734345
output resource name: customers/123456789/adGroupAds/9876565423/082734345
```
The resource name gets mangled on the way out and is unusable now.

**Comment by nwbirnie** [comment]
Hey folks, would it be possible to get this fixed over the next week please? We have another large body of work which depends on this feature, with a hard deadline in mid-July.

**Comment by miraleung** [comment]
Please feel free to try out PR #159.

**Comment by devchas** [comment]
Just tested, and it looks like it works. Thanks for the quick fix!
