### ISSUE TITLE
Version-neutral API Docs

### ISSUE THREAD

**Issue by hiranya911** [googleapis/api-common-java#31]
Publish API docs with version-neural permanent links to individual files. For example https://googleapis.github.io/api-common-java/apidocs/com/google/api/core/ApiFuture.html should redirect to the latest version of ApiFuture.html. Currently only way to access the above is by specifying a version [explicitly](https://googleapis.github.io/api-common-java/1.1.0/apidocs/com/google/api/core/ApiFuture.html).

**Comment by chingor13** [comment]
Awhile back, we started publishing the javadocs to googleapis.dev: https://googleapis.dev/java/api-common/latest/index.html
