### ISSUE TITLE
java.header uses Apache 2.0, but LICENSE is BSD-style.

### ISSUE THREAD

**Issue by Capstan** [googleapis/api-common-java#333]
They appear to disagree. Shouldn't the `java.header` template the extant `LICENSE` text? This is confusing the monorepo license analyzer.

**Comment by Capstan** [comment]
I'm not quite sure how the `java.header` file is consumed… is it for creation of new .java files in some editor?

**Comment by suztomo** [comment]
@Capstan In my other projects, Maven checks the header of Java files in the using the `java.header` file but seems this repository doesn't work.

Memo: GitHub says LICENSE file is BSD3

<img width="868" alt="Screen Shot 2022-03-15 at 6 02 28 PM" src="https://user-images.githubusercontent.com/28604/158479910-a4cd2405-7539-42a7-9af3-aaa98c6d1296.png">

java.header says it's Apache 2 https://github.com/googleapis/api-common-java/blob/main/java.header#L4

The Java code has BSD 3 license https://github.com/googleapis/api-common-java/blob/main/src/main/java/com/google/api/core/AbstractApiFuture.java


To investigate why `java.header` is not enforced. Potentially update `java.header` to follow LICENSE file.

**Comment by meltsufin** [comment]
There seems to be no consistency across Java repos in googleapis org in regards to Apache vs BSD licenses. This repo seems to be based on BSD. So, we should probably make it fully conformant with that.

**Comment by meltsufin** [comment]
Closing in accordance with @vam-google's comment.
