### ISSUE TITLE
Use PathTemplate for dispatching many paths

### ISSUE THREAD

**Issue by jhspaybar** [googleapis/api-common-java#39]
Looking at the PathTemplate class, it appears to implement proper parsing and variable capturing for the http options one can define in their proto.  I'm aware of grpc-gateway, but I would like a java native solution.  My concern is that there doesn't appear to be a way to input many paths for matching and parsing at once.  For example, if I wanted to expose 3 mapped RPCs it looks like I'd need to just iterate all 3 PathTemplates and take the first that matched anything.  This sounds prohibitively slow, so I was hoping to get some feedback if there's a better way I'm missing in the APIs.

**Comment by meltsufin** [comment]
Closing due to lack of interest from more users.
