### ISSUE TITLE
javadocs site is stale

### ISSUE THREAD

**Issue by igorbernstein2** [googleapis/api-common-java#93]
Hi,
It seems like the javadoc publishing hasn't kept up with the releases. It seems like the last time the javadocs were published is 1.7.0:
https://github.com/googleapis/api-common-java/tree/gh-pages

The current version of this library is 1.8.1. This is causing linking issues with google-cloud-bigtable's javadocs site.

**Comment by codyoss** [comment]
Thanks for the report, will look into it!

**Comment by codyoss** [comment]
Fixed with 2a407fce99837cc336a29dc22d5071a11672e30f
